swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /avotype:
    get:
      operationId: avotype.read_all
      tags:
        - Avotype
      summary: Read the entire set of Avotype
      description: Read the entire set of Avotype
      responses:
        200:
          description: Successfully read Avotype set operation
          schema:
            type: array
            items:
              properties:
                typeid:
                  type: integer
                  description: Id of the person
                type:
                  type: string
                  description: First name of the person
                avocado:
                  type: array
                  items:
                    properties:
                      id:
                        type: integer
                        description: Id of person this note is associated with
                      date:
                        type: string
                        description: Create date of this note
                      avgprice:
                        type: integer
                        description: content of this note
                      totalvol:
                        type: integer
                        description: content of this note
                      avo_a:
                        type: integer
                        description: content of this note
                      avo_b:
                        type: integer
                        description: content of this note
                      avo_c:
                        type: integer
                        description: content of this note
                      type:
                        type: integer
                        description: content of this note
                      region:
                        type: integer
                        description: content of this note

    post:
      operationId: avotype.create
      tags:
        - Avotype
      summary: Create a avotype
      description: Create a new avotype
      parameters:
        - name: avotype
          in: body
          description: avotype to create
          required: True
          schema:
            type: object
            properties:
              type:
                type: string
                description: Type of Avotype to create
      responses:
        201:
          description: Successfully created avotype
          schema:
            properties:
              typeid:
                type: integer
                description: Id of the Type
              type:
                type: string
                description: Type of avotype

  /avotype/{avotype_id}:
    get:
      operationId: avotype.read_one
      tags:
        - Avotype
      summary: Read one avotype
      description: Read one avotype
      parameters:
        - name: avotype_id
          in: path
          description: Id of the avotype to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read avotype from people data operation
          schema:
            type: object
            properties:
              typeid:
                type: integer
                description: Id of the avotype
              type:
                type: string
                description: Type of the avotype
              avocado:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      description: Id of person this note is associated with
                    date:
                      type: string
                      description: Create date of this note
                    avgprice:
                      type: integer
                      description: content of this note
                    totalvol:
                      type: integer
                      description: content of this note
                    avo_a:
                      type: integer
                      description: content of this note
                    avo_b:
                      type: integer
                      description: content of this note
                    avo_c:
                      type: integer
                      description: content of this note
                    type:
                      type: integer
                      description: content of this note
                    region:
                      type: integer
                      description: content of this note

    put:
      operationId: avotype.update
      tags:
        - Avotype
      summary: Update a avotype
      description: Update a avotype
      parameters:
        - name: avotype_id
          in: path
          description: Id the avotype to update
          type: integer
          required: True
        - name: avotype
          in: body
          schema:
            type: object
            properties:
              type:
                type: string
                description: Type of the Avotype
      responses:
        200:
          description: Successfully updated avotype
          schema:
            properties:
              typeid:
                type: integer
                description: Id of the avotype in the database
              type:
                type: string
                description: Type of the Avotype

    delete:
      operationId: avotype.delete
      tags:
        - Avotype
      summary: Delete a avotype from the avotype list
      description: Delete a avotype
      parameters:
        - name: avotype_id
          in: path
          type: integer
          description: Id of the avotype to delete
          required: true
      responses:
        200:
          description: Successfully deleted a avotype

  /avocado:
    get:
      operationId: avocado.read_all
      tags:
        - Avocado
      summary: Read the entire set of avocado, sorted by id
      description: Read the entire set of avocado, sorted by id
      responses:
        200:
          description: Successfully read avocado
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                  description: Id of person this note is associated with
                date:
                  type: string
                  description: Create date of this note
                avgprice:
                  type: integer
                  description: content of this note
                totalvol:
                  type: integer
                  description: content of this note
                avo_a:
                  type: integer
                  description: content of this note
                avo_b:
                  type: integer
                  description: content of this note
                avo_c:
                  type: integer
                  description: content of this note
                type:
                  type: object
                  properties:
                    typeid:
                      type: integer
                      description: Id of associated avotype
                    type:
                      type: string
                      description: Type of associated avotype
                region:
                  type: integer
                  description: content of this note
                  


  /avotype/{typeid}/avoregion/{regionid}/avocado:
    post:
      operationId: avocado.create
      tags:
        - Avocado
      summary: Create a avocado associated with a avotype
      description: Create a avocado associated with a avotype
      parameters:
        - name: typeid
          in: path
          description: Id of avotype associated with avocado
          type: integer
          required: True
        - name: regionid
          in: path
          description: Id of avoregion associated with avocado
          type: integer
          required: True
        - name: avocado
          in: body
          description: Text content of the avocado to create
          required: True
          schema:
            type: object
            properties:
              avgprice:
                type: integer
                description: content of this note
              totalvol:
                type: integer
                description: content of this note
              avo_a:
                type: integer
                description: content of this note
              avo_b:
                type: integer
                description: content of this note
              avo_c:
                type: integer
                description: content of this note
      responses:
        201:
          description: Successfully created a avocado
          schema:
            properties:
              id:
                type: integer
                description: Id of person this note is associated with
              date:
                type: string
                description: Create date of this note
              avgprice:
                type: integer
                description: content of this note
              totalvol:
                type: integer
                description: content of this note
              avo_a:
                type: integer
                description: content of this note
              avo_b:
                type: integer
                description: content of this note
              avo_c:
                type: integer
                description: content of this note
              type:
                type: object
                properties:
                  typeid:
                    type: integer
                    description: Id of associated avotype
                  type:
                    type: string
                    description: Type of associated avotype
              region:
                type: object
                properties:
                  regionid:
                    type: integer
                    description: Id of associated avoregion
                  region:
                    type: string
                    description: Type of associated avoregion

  /avocado/{id}:
    get:
      operationId: avocado.read_one
      tags:
        - Avocado
      summary: Read a particular avocado associated with a avotype
      description: Read a particular avocado associated with a avotype
      parameters:
        - name: id
          in: path
          description: Id of avocado associated with avotype
          type: integer
          required: True
      responses:
        200:
          description: Successfully read avocado
          schema:
            type: object
            properties:
              id:
                type: integer
                description: Id of person this note is associated with
              date:
                type: string
                description: Create date of this note
              avgprice:
                type: integer
                description: content of this note
              totalvol:
                type: integer
                description: content of this note
              avo_a:
                type: integer
                description: content of this note
              avo_b:
                type: integer
                description: content of this note
              avo_c:
                type: integer
                description: content of this note
              type:
                type: object
                properties:
                  typeid:
                    type: integer
                    description: Id of associated avotype
                  type:
                    type: string
                    description: Type of associated avotype
              region:
                type: object
                properties:
                  regionid:
                    type: integer
                    description: Id of associated avoregion
                  region:
                    type: string
                    description: Type of associated avoregion

    put:
      operationId: avocado.update
      tags:
        - Avocado
      summary: Update a avocado
      description: Update a avocado
      parameters:
        - name: id
          in: path
          description: Id of the avocado
          type: integer
          required: True
        - name: avocado
          in: body
          schema:
            type: object
            properties:
              avgprice:
                type: integer
                description: content of this note
              totalvol:
                type: integer
                description: content of this note
              avo_a:
                type: integer
                description: content of this note
              avo_b:
                type: integer
                description: content of this note
              avo_c:
                type: integer
                description: content of this note
      responses:
        200:
          description: Successfully updated note
          schema:
            properties:
              id:
                type: integer
                description: Id of person this note is associated with
              date:
                type: string
                description: Create date of this note
              avgprice:
                type: integer
                description: content of this note
              totalvol:
                type: integer
                description: content of this note
              avo_a:
                type: integer
                description: content of this note
              avo_b:
                type: integer
                description: content of this note
              avo_c:
                type: integer
                description: content of this note
              type:
                type: integer
                description: content of this note
              region:
                type: integer
                description: content of this note

    delete:
      operationId: avocado.delete
      tags:
        - Avocado
      summary: Delete a avocado
      description: Delete a avocado
      parameters:
        - name: id
          in: path
          description: Id of avocado
          type: integer
          required: True
      responses:
        200:
          description: Successfully deleted a avocado

